import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/common/Navbar";
import { Footer} from "@/components/ui/common/Footer";
import { ThemeProvider } from "next-themes";
import { DirectionProvider } from "@radix-ui/react-direction";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Muashir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  lang="ar" dir="rtl"  suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
            <DirectionProvider dir="rtl">
              <Navbar />
              {children}
              <Footer />
            </DirectionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
