import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/common/Navbar";
import { Footer} from "@/components/ui/common/Footer";
import { NextIntlClientProvider } from "next-intl";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Muashir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {

const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <html  lang={lang} dir={dir}  suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <NextIntlClientProvider>
                <Navbar />
                {children}
                <Footer />
                </NextIntlClientProvider>
      </body>
    </html>
  );
}
