import type { Metadata } from "next";
import LocalFont from "next/font/local";
import { Geist} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/common/Navbar";
import { Footer} from "@/components/ui/common/Footer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { ThemeProvider } from "next-themes";
import { routing } from "@/src/i18n/routing";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const Watad = LocalFont({
  src: [{
    path: '../../../public/fonts/Watad.otf'
  },],
  variable: "--font-Watad",
  
});

export const metadata: Metadata = {
  title: "Muashir",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {

  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  setRequestLocale(locale);

  const messages = await getMessages();

const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html  lang={locale} dir={dir}  suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${Watad.variable} font-sans rtl:font-Watad antialiased`}>
            <ThemeProvider attribute="class" enableSystem defaultTheme="system">
              <NextIntlClientProvider messages={messages}>
                <Navbar />
                {children}
                <Footer />
                </NextIntlClientProvider>
            </ThemeProvider>
      </body>
    </html>
  );
}
